# Create the docker container for the backend
FROM python:3.7.3-alpine3.9

COPY requirements.txt /app/
WORKDIR /app
RUN pip install --upgrade pip \
  && pip install -r requirements.txt

ENV PATH="/scripts:${PATH}"

COPY docker/ /scripts/
RUN dos2unix /scripts/*
