# Create the docker container for the backend
FROM python:3.7.3-alpine3.9

COPY requirements.txt /app/
WORKDIR /app
RUN apk add --update --no-cache --virtual .deps libpq
RUN apk add --no-cache --virtual .build-deps \
    gcc \
    musl-dev \
    postgresql-dev \
  && pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir -r requirements.txt \
  && apk del --no-cache .build-deps

ENV PATH="/scripts:${PATH}"

COPY docker/ /scripts/
RUN dos2unix /scripts/*
