# Author: Andrew Kassab
# Date: 05-03-19
# Description: Class to store a playlist, generated by our factory 
# classes.

class Playlist:

    def __init__(self, songs, name, image):
       self.songs = songs
       slef.name = name
       self.image = image

    def toJson():
        # TODO: Generate json data for the playlist?
