# This is an interface for inheriting classes that
# defines the proccess for which a playlist should
# be generated by the groupify app.

from abc import ABC, abstractmethod
# TODO: Import necessary objects

class PlaylistFactory(ABC):

    def __init__(self, users, length):
        self.users = users
        self.playlist_length = length
        self.common_songs = []
        self.union_songs = []
        self.playlist = None
        super().__init__()

    # Creates the playlist by running appropriate methods to filter songs
    @abstractmethod
    def create(self): 
        pass 

    # Create a union of all user's saved tracks
    def __union_tracks(self):
        for user in self.users:
            # avoid duplicates , but make sure to add user to track object
            for track in user.saved_tracks:
                if track.song_id in self.union_songs:
                    self.union_songs[songid].add_user(user)
                else: 
                    self.union_songs[track.song_id] = track

    # Create the list of common tracks 
    def __filter_common_tracks():
        min_required = len(users)/2 
        for track in union_songs:
            if track.amt_saved >= min_required:
                common_songs[track.song_id] = track

    # Filter common tracks by most played
    # TODO:
    def __filter_common_most_played(self): 
        pass

    # Filter unioned tracks by most played
    # TODO:
    def __filter_union_most_played(self): 
        pass

    # Lvl 3 filter
    # TODO:
    @abstractmethod
    def __filter_union_similarities(self): 
        pass

    # Lvl 4 filter
    # TODO:
    @abstractmethod
    def __filter_by_length(self): 
        pass

    # Combine union list and intersect list
    def combine(self):

        # Convert both lists to sets
        union_set = set(union_songs)
        intersect_set = set(intersect_songs)

        # Merge the sets
        union_set.union(intersect_songs)

        # Finally convert to list
        songs = list(union_set)

    def create_playlist():

        # TODO:
        # playlist_name = Groupify-DATE
        # playlist_image = groupify album art by default (?)

        playlist = playlist( songs, playlist_name, playlist_image )
        return playlist
